# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxcalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='name',
            field=models.CharField(default='', max_length=140),
        ),
    ]
