# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxcalc', '0002_medication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='concentration',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
