# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxcalc', '0003_medication_concentration'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
