# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxcalc', '0005_auto_20160120_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(default='', max_length=140, unique=True),
        ),
    ]
