# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxcalc', '0006_auto_20160120_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
