# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxcalc', '0007_medication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='factor',
            field=models.FloatField(default=0.0),
        ),
    ]
