# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxcalc', '0008_medication_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['category']},
        ),
    ]
