# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxcalc', '0009_auto_20160121_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='admin',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
