# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxcalc', '0011_medication_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['category', 'name']},
        ),
    ]
