# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rxcalc', '0013_delete_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=140, unique=True)),
                ('slug', models.SlugField(default='', max_length=40, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=140)),
                ('desc', models.TextField(blank=True, default='')),
                ('factor', models.FloatField(default=0.0)),
                ('concentration', models.CharField(blank=True, default='', max_length=140)),
                ('admin', models.CharField(blank=True, default='', max_length=140)),
            ],
            options={
                'ordering': ['category', 'name'],
                'abstract': False,
            },
        ),
    ]
