# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cri',
            name='time',
            field=models.CharField(default='', max_length=3),
        ),
    ]
