# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_cri_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cri',
            name='factor',
            field=models.FloatField(default=0.0),
        ),
    ]
