# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_cri_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cri',
            name='recommended_rates',
            field=models.CharField(default='', max_length=10),
        ),
    ]
