# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='client_desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
