# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 22:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_sheets', '0002_auto_20160318_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txsheet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
