# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 22:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_sheets', '0003_auto_20160319_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='txsheet',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2016, 3, 20)),
            preserve_default=False,
        ),
    ]
