# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_sheets', '0004_txsheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txitem',
            name='unit',
            field=models.CharField(choices=[('mL', 'mLs'), ('C', 'capsules'), ('T', 'tablets')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='txsheet',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
