# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_sheets', '0005_auto_20160323_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txsheet',
            name='comment',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
